stages:
  - login
  - package
  - push

login:
  stage: login
  image:
    name: alpine/helm 
    entrypoint: [""]
  script: 
    -  "echo ${HARBOR_PASSWORD} | helm registry login ${HARBOR_HOST} --username ${HARBOR_USERNAME} --password-stdin"
  
package:
  stage: package
  image:
    name: alpine/helm 
    entrypoint: [""]
  script: 
    - "for chart in $(ls charts/); do helm package charts/${chart}; done"
  artifacts:
    paths:
      - "*.tgz"
  
push:
  stage: push
  image:
    name: alpine/helm 
    entrypoint: [""]
  script: 
    - "echo ${HARBOR_PASSWORD} | helm registry login ${HARBOR_HOST} --username ${HARBOR_USERNAME} --password-stdin"
    - "for chart in $(find . -type f -name *.tgz); do helm push ${chart} ${HARBOR_OCI}/helm-charts; done"
  artifacts:
    paths:
      - "*.tgz"
