{{- if .Values.manyfold.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.manyfold.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.manyfold.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-migrations"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
